a=findobj(gcf); % get the handles associated with the current figure

allaxes=findall(a,'Type','axes');
alltext=findall(a,'Type','text');

set(allaxes,'FontName','Times','LineWidth',1,'FontSize',13,'FontWeight','bold');
set(alltext,'FontName','Times','FontSize',13,'FontWeight','bold')

set(gcf, 'PaperUnits', 'inches');

krare=2.5;
x_width=krare*5/3 ;
y_width=krare*4/3;
set(gcf, 'PaperPosition', [0 0 x_width y_width]); 

set(gca, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'in'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'off'      , ...
    'XGrid'       , 'off'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );

print('F9-XXAO', '-dtiff', '-r300'); %<-Save as PNG with 300 DPI
