%**************************************************************************************************
%Reference:  C. Garcia-Martinez, M. Lozano, F. Herrera, D. Molina, and A.M. Sanchez,
%                   "Global and local real-coded genetic algorithms based on parent-centric
%                      crossover operators," European Journal of Operatoral Research, vol. 185,
%                      pp. 1088¨C1113, 2008.
%
% Note: We obtained the C source code from the authors, and developed the
%           MATLAB source code based on the C source code.
%**************************************************************************************************

function [GBEST, cg_curve]=GL25(N,MaxFEs,lb,ub,dim,fobj)
tic;

format long;
format compact;

GBEST = zeros(1,dim);
fes = 0;
cg_curve=[];
t = 1;
GM_fit = zeros(N, 1);
lu = [lb .* ones(1, dim); ub .* ones(1, dim)];

% Choose the problems to be tested. Please note that for test functions F7
% and F25, the global optima are out of the initialization range. For these
% two test functions, we do not need to judge whether the variable violates
% the boundaries during the evolution after the initialization.

% Define the dimension of the problem
n = dim;

% Main body which is developed according to the C source code provided
% by the authors

rand('seed', sum(100 * clock));

popsize = N;

% Initialize the male group of the global search
GM = repmat(lu(1, :), popsize, 1) + rand(popsize, n) .* (repmat(lu(2, :) - lu(1, :), popsize, 1));
for i = 1 : N
    GM_fit(i) = fobj(GM(i, :));
    fes = fes + 1;
end

% Initialize the female group of the global search
[~, fitindex] = sort(GM_fit);

GF = GM(fitindex(1 : N/2), :);
GF_fit = GM_fit(fitindex(1 : N/2), :);

% Record the number of offspring generated by the female parent
numTimesMother = zeros(N/2, 1);

% Judge the global search or the local search: j = 0 mean the global
% search and j = 1 means the local search
j = 0;

FES = popsize;
% while FES < n * 10000
while fes <= MaxFEs

    'GL_25'
    t

    if FES > n * 10000 * 0.25 && j == 0

        popsize = round(N/4);

        [~, fitindex] = sort(GM_fit);
        % Initialize the male group of the local search
        GM = GM(fitindex(1 : round(N/4)), :);
        GM_fit = GM_fit(fitindex(1 : round(N/4)), :);

        % Initialize the female group of the local search
        GF = GM(1 : ceil(N/80), :);
        GF_fit = GM_fit(1 : ceil(N/80), :);

        % Updat the number of offspring generated by the female
        % parent
        numTimesMother = zeros(ceil(N/80), 1);

        j = 1;

    end

    % Uniform fertility selection
    [~, Timesindex] = min(numTimesMother);

    mother = GF(Timesindex, :);
    mother_fit = GF_fit(Timesindex, :);

    numTimesMother(Timesindex) = numTimesMother(Timesindex) + 1;

    % Negative assortative mating
    temp = floor(rand(1, ceil(N/80)) * popsize) + 1;
    temp_father = GM(temp, :);
    temp_father_fit = GM_fit(temp, :);

    Edistance = sum((ones(ceil(N/80), 1) * mother-temp_father) .^ 2, 2);

    [~, Edistanceindex] = max(Edistance);

    father = temp_father(Edistanceindex, :);
    father_fit = temp_father_fit(Edistanceindex, :);

    %PBX-alfa
    temp = abs(mother - father);
    L = max(lu(1, :), mother - temp .* 0.8);
    U = min(lu(2, :), mother + temp .* 0.8);
    offspring = L + rand(1, n) .* (U-L);

    % Evaluation
    offspring_fit = fobj(offspring);
    fes = fes + 1;

    % Replace the worst individual in the population
    if offspring_fit < mother_fit

        [~, fitindex] = max(GM_fit);
        GM(fitindex, :) = mother;
        GM_fit(fitindex, :) = mother_fit;

        GF(Timesindex, :) = offspring;
        GF_fit(Timesindex, :) = offspring_fit;

        numTimesMother(Timesindex, :) = 0;

    elseif offspring_fit < max(GM_fit)

        [~, fitindex] = max(GM_fit);
        GM(fitindex, :) = offspring;
        GM_fit(fitindex, :) = offspring_fit;

    end

    FES = FES + 1;
    
    cg_curve(t) = min(GF_fit);
    t = t + 1;
end

toc;