% GSA code v1.1.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
% “GSA: A Gravitational Search Algorithm? Information sciences, vol. 179,
% no. 13, pp. 2232-2248, 2009."

% Gravitational Search Algorithm.
function [Lbest,Convergence_curve]=GSA(SearchAgents_no,MaxFEs,lb,ub,dim,fobj)%GSA(F_index,N,max_it,ElitistCheck,min_flag,Rpower)
N=SearchAgents_no;
low=lb;
up=ub;
min_flag=1;
Rpower=1;
ElitistCheck=1;
F_index=1;
FEs=0;
%V:   Velocity.
%a:   Acceleration.
%M:   Mass.  Ma=Mp=Mi=M;
%dim: Dimension of the test function.
%N:   Number of agents.
%X:   Position of agents. dim-by-N matrix.
%R:   Distance between agents in search space.
%[low-up]: Allowable range for search space.
%Rnorm:  Norm in eq.8.
%Rpower: Power of R in eq.7.
 
 Rnorm=2; 
 
%random initialization for agents.
X=initializationGSA(dim,N,up,low); 

%create the best so far chart and average fitnesses chart.
BestChart=[];MeanChart=[];

V=zeros(N,dim);
t=1;Convergence_curve=[];
while FEs < MaxFEs %iteration=1:max_it
%     iteration
    
    %Checking allowable range. 
    X=space_bound(X,up,low); 

    %Evaluation of agents. 
    %fitness=evaluateF(X,F_index); 
    for i=1:N
       fitness(i)=fobj(X(i,:));
       FEs=FEs+1;
    end    
    if min_flag==1
    [best best_X]=min(fitness); %minimization.
    else
    [best best_X]=max(fitness); %maximization.
    end        
    
    if t==1
       Fbest=best;Lbest=X(best_X,:);
    end
    if min_flag==1
      if best<Fbest  %minimization.
       Fbest=best;Lbest=X(best_X,:);
      end
    else 
      if best>Fbest  %maximization
       Fbest=best;Lbest=X(best_X,:);
      end
    end
      
Convergence_curve(t)= Fbest;
%MeanChart=[MeanChart mean(fitness)];

%Calculation of M. eq.14-20
[M]=massCalculation(fitness,min_flag); 

%Calculation of Gravitational constant. eq.13.
G=Gconstant(t,MaxFEs); 

%Calculation of accelaration in gravitational field. eq.7-10,21.
a=Gfield(M,X,G,Rnorm,Rpower,ElitistCheck,t,MaxFEs);

%Agent movement. eq.11-12
[X,V]=move(X,a,V);
t=t+1;
end %iteration

